/** Real-language listings for 0/1 knapsack (bottom-up), line-mapped to the
 *  pseudocode in index.ts. Items are 1-based in the table and 0-based in the
 *  arrays, so item i has weight w[i - 1]. The walk back treats a tie as "not
 *  taken", like the generator. Display only; src/algorithms/_code runs them
 *  against `reference`. */

import { listing } from '@/algorithms/_code/listing';
import type { CodeListing, RealLanguage } from '@/algorithms/types';

const N = 7;

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  bottomup: {
    js: listing(N, [
      ['function knapsack(w, v, W) {'],
      ['  const n = w.length;', 1],
      ['  const dp = Array.from({ length: n + 1 }, () => new Array(W + 1).fill(0));', 1],
      ['  for (let i = 1; i <= n; i++) {', 2],
      ['    for (let c = 0; c <= W; c++) {', 3],
      ['      dp[i][c] = dp[i - 1][c];', 4],
      ['      if (w[i - 1] <= c) {', 5],
      ['        dp[i][c] = Math.max(dp[i][c], dp[i - 1][c - w[i - 1]] + v[i - 1]);', 6],
      ['      }'],
      ['    }'],
      ['  }'],
      ['  const taken = [];', 7],
      ['  for (let i = n, c = W; i >= 1; i--) {', 7],
      ['    if (dp[i][c] !== dp[i - 1][c]) {', 7],
      ['      taken.unshift(i);', 7],
      ['      c -= w[i - 1];', 7],
      ['    }'],
      ['  }'],
      ['  return { best: dp[n][W], taken };'],
      ['}'],
    ]),
    python: listing(N, [
      ['def knapsack(w, v, W):'],
      ['    n = len(w)', 1],
      ['    dp = [[0] * (W + 1) for _ in range(n + 1)]', 1],
      ['    for i in range(1, n + 1):', 2],
      ['        for c in range(W + 1):', 3],
      ['            dp[i][c] = dp[i - 1][c]', 4],
      ['            if w[i - 1] <= c:', 5],
      ['                dp[i][c] = max(dp[i][c], dp[i - 1][c - w[i - 1]] + v[i - 1])', 6],
      ['    taken, c = [], W', 7],
      ['    for i in range(n, 0, -1):', 7],
      ['        if dp[i][c] != dp[i - 1][c]:', 7],
      ['            taken.insert(0, i)', 7],
      ['            c -= w[i - 1]', 7],
      ['    return dp[n][W], taken'],
    ]),
    cpp: listing(N, [
      ['pair<int, vector<int>> knapsack(const vector<int>& w, const vector<int>& v, int W) {'],
      ['    int n = w.size();', 1],
      ['    vector<vector<int>> dp(n + 1, vector<int>(W + 1, 0));', 1],
      ['    for (int i = 1; i <= n; i++) {', 2],
      ['        for (int c = 0; c <= W; c++) {', 3],
      ['            dp[i][c] = dp[i - 1][c];', 4],
      ['            if (w[i - 1] <= c) {', 5],
      ['                dp[i][c] = max(dp[i][c], dp[i - 1][c - w[i - 1]] + v[i - 1]);', 6],
      ['            }'],
      ['        }'],
      ['    }'],
      ['    vector<int> taken;', 7],
      ['    for (int i = n, c = W; i >= 1; i--) {', 7],
      ['        if (dp[i][c] != dp[i - 1][c]) {', 7],
      ['            taken.insert(taken.begin(), i);', 7],
      ['            c -= w[i - 1];', 7],
      ['        }'],
      ['    }'],
      ['    return {dp[n][W], taken};'],
      ['}'],
    ]),
    java: listing(N, [
      ['record Result(int best, List<Integer> taken) {}'],
      [''],
      ['static Result knapsack(int[] w, int[] v, int W) {'],
      ['    int n = w.length;', 1],
      ['    int[][] dp = new int[n + 1][W + 1];', 1],
      ['    for (int i = 1; i <= n; i++) {', 2],
      ['        for (int c = 0; c <= W; c++) {', 3],
      ['            dp[i][c] = dp[i - 1][c];', 4],
      ['            if (w[i - 1] <= c) {', 5],
      ['                dp[i][c] = Math.max(dp[i][c], dp[i - 1][c - w[i - 1]] + v[i - 1]);', 6],
      ['            }'],
      ['        }'],
      ['    }'],
      ['    List<Integer> taken = new ArrayList<>();', 7],
      ['    for (int i = n, c = W; i >= 1; i--) {', 7],
      ['        if (dp[i][c] != dp[i - 1][c]) {', 7],
      ['            taken.add(0, i);', 7],
      ['            c -= w[i - 1];', 7],
      ['        }'],
      ['    }'],
      ['    return new Result(dp[n][W], taken);'],
      ['}'],
    ]),
  },
};
