/** Real-language listings for Kahn's topological sort, line-mapped to the
 *  pseudocode in index.ts. Building the adjacency lists counts the in-degrees
 *  (line 1); sorting each list gives "in ascending v" (line 5). The queue is
 *  first in, first out. Display only; topo-sort/code.test.ts runs all four
 *  against `reference`. */

import { listing } from '@/algorithms/_code/listing';
import type { CodeListing, RealLanguage } from '@/algorithms/types';

const N = 8;

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  kahn: {
    js: listing(N, [
      ['function topoSort(n, arcs) {'],
      ['  const adj = Array.from({ length: n }, () => []);', 1],
      ['  const indeg = new Array(n).fill(0);', 1],
      ['  for (const [a, b] of arcs) {', 1],
      ['    adj[a].push(b);', 1],
      ['    indeg[b]++;', 1],
      ['  }'],
      ['  for (const list of adj) list.sort((x, y) => x - y);', 5],
      ['  const queue = [];', 2],
      ['  for (let v = 0; v < n; v++) if (indeg[v] === 0) queue.push(v);', 2],
      ['  const order = [];', 2],
      ['  while (queue.length > 0) {', 3],
      ['    const u = queue.shift();', 4],
      ['    order.push(u);', 4],
      ['    for (const v of adj[u]) {', 5],
      ['      indeg[v]--;', 6],
      ['      if (indeg[v] === 0) queue.push(v);', 7],
      ['    }'],
      ['  }'],
      ['  return order;', 8],
      ['}'],
    ]),
    python: listing(N, [
      ['def topo_sort(n, arcs):'],
      ['    adj = [[] for _ in range(n)]', 1],
      ['    indeg = [0] * n', 1],
      ['    for a, b in arcs:', 1],
      ['        adj[a].append(b)', 1],
      ['        indeg[b] += 1', 1],
      ['    for lst in adj:', 5],
      ['        lst.sort()', 5],
      ['    queue = deque(v for v in range(n) if indeg[v] == 0)', 2],
      ['    order = []', 2],
      ['    while queue:', 3],
      ['        u = queue.popleft()', 4],
      ['        order.append(u)', 4],
      ['        for v in adj[u]:', 5],
      ['            indeg[v] -= 1', 6],
      ['            if indeg[v] == 0:', 7],
      ['                queue.append(v)', 7],
      ['    return order', 8],
    ]),
    cpp: listing(N, [
      ['vector<int> topoSort(int n, const vector<pair<int, int>>& arcs) {'],
      ['    vector<vector<int>> adj(n);', 1],
      ['    vector<int> indeg(n, 0);', 1],
      ['    for (auto [a, b] : arcs) {', 1],
      ['        adj[a].push_back(b);', 1],
      ['        indeg[b]++;', 1],
      ['    }'],
      ['    for (auto& list : adj) sort(list.begin(), list.end());', 5],
      ['    queue<int> q;', 2],
      ['    for (int v = 0; v < n; v++) if (indeg[v] == 0) q.push(v);', 2],
      ['    vector<int> order;', 2],
      ['    while (!q.empty()) {', 3],
      ['        int u = q.front();', 4],
      ['        q.pop();', 4],
      ['        order.push_back(u);', 4],
      ['        for (int v : adj[u]) {', 5],
      ['            indeg[v]--;', 6],
      ['            if (indeg[v] == 0) q.push(v);', 7],
      ['        }'],
      ['    }'],
      ['    return order;', 8],
      ['}'],
    ]),
    java: listing(N, [
      ['static List<Integer> topoSort(int n, int[][] arcs) {'],
      ['    List<List<Integer>> adj = new ArrayList<>();', 1],
      ['    for (int v = 0; v < n; v++) adj.add(new ArrayList<>());', 1],
      ['    int[] indeg = new int[n];', 1],
      ['    for (int[] arc : arcs) {', 1],
      ['        adj.get(arc[0]).add(arc[1]);', 1],
      ['        indeg[arc[1]]++;', 1],
      ['    }'],
      ['    for (List<Integer> list : adj) Collections.sort(list);', 5],
      ['    ArrayDeque<Integer> queue = new ArrayDeque<>();', 2],
      ['    for (int v = 0; v < n; v++) if (indeg[v] == 0) queue.add(v);', 2],
      ['    List<Integer> order = new ArrayList<>();', 2],
      ['    while (!queue.isEmpty()) {', 3],
      ['        int u = queue.poll();', 4],
      ['        order.add(u);', 4],
      ['        for (int v : adj.get(u)) {', 5],
      ['            indeg[v]--;', 6],
      ['            if (indeg[v] == 0) queue.add(v);', 7],
      ['        }'],
      ['    }'],
      ['    return order;', 8],
      ['}'],
    ]),
  },
};
