/** Real-language listings for the binary min-heap, line-mapped to the
 *  pseudocode in index.ts. The heap is a growable array (JS array, Python
 *  list, C++ vector, Java ArrayList), so `n` is its length: push/append is
 *  "a[n] = x; n = n + 1" and pop is "n = n - 1". extractMin on an empty heap
 *  returns null / None, and −1 in C++ and Java (values here are 0–99).
 *  Display only; heap/code.test.ts runs all four against `reference`. */

import { listing } from '@/algorithms/_code/listing';
import type { CodeListing, RealLanguage } from '@/algorithms/types';

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  insert: {
    js: listing(7, [
      ['function insert(a, x) {', 1],
      ['  a.push(x);', 2],
      ['  let i = a.length - 1;', 2],
      ['  while (i > 0) {', 3],
      ['    const p = Math.floor((i - 1) / 2);', 4],
      ['    if (a[p] <= a[i]) break;', 5],
      ['    [a[i], a[p]] = [a[p], a[i]];', 6],
      ['    i = p;', 7],
      ['  }'],
      ['}'],
    ]),
    python: listing(7, [
      ['def insert(a, x):', 1],
      ['    a.append(x)', 2],
      ['    i = len(a) - 1', 2],
      ['    while i > 0:', 3],
      ['        p = (i - 1) // 2', 4],
      ['        if a[p] <= a[i]:', 5],
      ['            break', 5],
      ['        a[i], a[p] = a[p], a[i]', 6],
      ['        i = p', 7],
    ]),
    cpp: listing(7, [
      ['void insert(vector<int>& a, int x) {', 1],
      ['    a.push_back(x);', 2],
      ['    int i = (int)a.size() - 1;', 2],
      ['    while (i > 0) {', 3],
      ['        int p = (i - 1) / 2;', 4],
      ['        if (a[p] <= a[i]) break;', 5],
      ['        swap(a[i], a[p]);', 6],
      ['        i = p;', 7],
      ['    }'],
      ['}'],
    ]),
    java: listing(7, [
      ['static void insert(List<Integer> a, int x) {', 1],
      ['    a.add(x);', 2],
      ['    int i = a.size() - 1;', 2],
      ['    while (i > 0) {', 3],
      ['        int p = (i - 1) / 2;', 4],
      ['        if (a.get(p) <= a.get(i)) break;', 5],
      ['        Collections.swap(a, i, p);', 6],
      ['        i = p;', 7],
      ['    }'],
      ['}'],
    ]),
  },
  extract: {
    js: listing(14, [
      ['function extractMin(a) {', 1],
      ['  if (a.length === 0) return null;', 2],
      ['  const min = a[0];', 3],
      ['  const last = a.pop();', 3],
      ['  if (a.length > 0) a[0] = last;', 4],
      ['  let i = 0;', 5],
      ['  while (true) {', 6],
      ['    const l = 2 * i + 1, r = 2 * i + 2;', 7],
      ['    if (l >= a.length) break;', 8],
      ['    let c = l;', 9],
      ['    if (r < a.length && a[r] < a[l]) c = r;', 10],
      ['    if (a[i] <= a[c]) break;', 11],
      ['    [a[i], a[c]] = [a[c], a[i]];', 12],
      ['    i = c;', 13],
      ['  }'],
      ['  return min;', 14],
      ['}'],
    ]),
    python: listing(14, [
      ['def extract_min(a):', 1],
      ['    if not a:', 2],
      ['        return None', 2],
      ['    min_value = a[0]', 3],
      ['    last = a.pop()', 3],
      ['    if a:', 4],
      ['        a[0] = last', 4],
      ['    i = 0', 5],
      ['    while True:', 6],
      ['        l, r = 2 * i + 1, 2 * i + 2', 7],
      ['        if l >= len(a):', 8],
      ['            break', 8],
      ['        c = l', 9],
      ['        if r < len(a) and a[r] < a[l]:', 10],
      ['            c = r', 10],
      ['        if a[i] <= a[c]:', 11],
      ['            break', 11],
      ['        a[i], a[c] = a[c], a[i]', 12],
      ['        i = c', 13],
      ['    return min_value', 14],
    ]),
    cpp: listing(14, [
      ['int extractMin(vector<int>& a) {', 1],
      ['    if (a.empty()) return -1; // empty heap', 2],
      ['    int minValue = a[0];', 3],
      ['    int last = a.back();', 3],
      ['    a.pop_back();', 3],
      ['    if (!a.empty()) a[0] = last;', 4],
      ['    int n = a.size(), i = 0;', 5],
      ['    while (true) {', 6],
      ['        int l = 2 * i + 1, r = 2 * i + 2;', 7],
      ['        if (l >= n) break;', 8],
      ['        int c = l;', 9],
      ['        if (r < n && a[r] < a[l]) c = r;', 10],
      ['        if (a[i] <= a[c]) break;', 11],
      ['        swap(a[i], a[c]);', 12],
      ['        i = c;', 13],
      ['    }'],
      ['    return minValue;', 14],
      ['}'],
    ]),
    java: listing(14, [
      ['static int extractMin(List<Integer> a) {', 1],
      ['    if (a.isEmpty()) return -1; // empty heap', 2],
      ['    int minValue = a.get(0);', 3],
      ['    int last = a.remove(a.size() - 1);', 3],
      ['    if (!a.isEmpty()) a.set(0, last);', 4],
      ['    int n = a.size(), i = 0;', 5],
      ['    while (true) {', 6],
      ['        int l = 2 * i + 1, r = 2 * i + 2;', 7],
      ['        if (l >= n) break;', 8],
      ['        int c = l;', 9],
      ['        if (r < n && a.get(r) < a.get(l)) c = r;', 10],
      ['        if (a.get(i) <= a.get(c)) break;', 11],
      ['        Collections.swap(a, i, c);', 12],
      ['        i = c;', 13],
      ['    }'],
      ['    return minValue;', 14],
      ['}'],
    ]),
  },
  build: {
    js: listing(12, [
      ['function buildHeap(a) {', 1],
      ['  for (let k = Math.floor(a.length / 2) - 1; k >= 0; k--) {', 2],
      ['    siftDown(a, k);', 3],
      ['  }'],
      ['}'],
      [''],
      ['function siftDown(a, i) {', 4],
      ['  while (true) {', 5],
      ['    const l = 2 * i + 1, r = 2 * i + 2;', 6],
      ['    if (l >= a.length) return;', 7],
      ['    let c = l;', 8],
      ['    if (r < a.length && a[r] < a[l]) c = r;', 9],
      ['    if (a[i] <= a[c]) return;', 10],
      ['    [a[i], a[c]] = [a[c], a[i]];', 11],
      ['    i = c;', 12],
      ['  }'],
      ['}'],
    ]),
    python: listing(12, [
      ['def build_heap(a):', 1],
      ['    for k in range(len(a) // 2 - 1, -1, -1):', 2],
      ['        sift_down(a, k)', 3],
      [''],
      ['def sift_down(a, i):', 4],
      ['    while True:', 5],
      ['        l, r = 2 * i + 1, 2 * i + 2', 6],
      ['        if l >= len(a):', 7],
      ['            return', 7],
      ['        c = l', 8],
      ['        if r < len(a) and a[r] < a[l]:', 9],
      ['            c = r', 9],
      ['        if a[i] <= a[c]:', 10],
      ['            return', 10],
      ['        a[i], a[c] = a[c], a[i]', 11],
      ['        i = c', 12],
    ]),
    cpp: listing(12, [
      ['void siftDown(vector<int>& a, int i);', 4],
      [''],
      ['void buildHeap(vector<int>& a) {', 1],
      ['    for (int k = (int)a.size() / 2 - 1; k >= 0; k--) {', 2],
      ['        siftDown(a, k);', 3],
      ['    }'],
      ['}'],
      [''],
      ['void siftDown(vector<int>& a, int i) {', 4],
      ['    int n = a.size();', 5],
      ['    while (true) {', 5],
      ['        int l = 2 * i + 1, r = 2 * i + 2;', 6],
      ['        if (l >= n) return;', 7],
      ['        int c = l;', 8],
      ['        if (r < n && a[r] < a[l]) c = r;', 9],
      ['        if (a[i] <= a[c]) return;', 10],
      ['        swap(a[i], a[c]);', 11],
      ['        i = c;', 12],
      ['    }'],
      ['}'],
    ]),
    java: listing(12, [
      ['static void buildHeap(List<Integer> a) {', 1],
      ['    for (int k = a.size() / 2 - 1; k >= 0; k--) {', 2],
      ['        siftDown(a, k);', 3],
      ['    }'],
      ['}'],
      [''],
      ['static void siftDown(List<Integer> a, int i) {', 4],
      ['    int n = a.size();', 5],
      ['    while (true) {', 5],
      ['        int l = 2 * i + 1, r = 2 * i + 2;', 6],
      ['        if (l >= n) return;', 7],
      ['        int c = l;', 8],
      ['        if (r < n && a.get(r) < a.get(l)) c = r;', 9],
      ['        if (a.get(i) <= a.get(c)) return;', 10],
      ['        Collections.swap(a, i, c);', 11],
      ['        i = c;', 12],
      ['    }'],
      ['}'],
    ]),
  },
};
