/** Real-language listings for union-find with union by rank (ties: the smaller
 *  id on top) and two-pass path compression, line-mapped to the pseudocode in
 *  index.ts. `union` is a keyword in C++, so the C++ listing calls it `unite`.
 *  Display only; union-find/code.test.ts runs all four against `reference`. */

import { listing } from '@/algorithms/_code/listing';
import type { CodeListing, RealLanguage } from '@/algorithms/types';

const N = 13;

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  rank: {
    js: listing(N, [
      ['function find(parent, x) {', 1],
      ['  let r = x;', 2],
      ['  while (parent[r] !== r) r = parent[r];', 3],
      ['  while (parent[x] !== r) {', 4],
      ['    const next = parent[x];', 5],
      ['    parent[x] = r;', 5],
      ['    x = next;', 5],
      ['  }'],
      ['  return r;', 6],
      ['}'],
      [''],
      ['function union(parent, rank, a, b) {', 7],
      ['  let ra = find(parent, a), rb = find(parent, b);', 8],
      ['  if (ra === rb) return;', 9],
      ['  if (rank[ra] < rank[rb]) [ra, rb] = [rb, ra];', 10],
      ['  else if (rank[ra] === rank[rb] && rb < ra) [ra, rb] = [rb, ra];', 11],
      ['  parent[rb] = ra;', 12],
      ['  if (rank[ra] === rank[rb]) rank[ra]++;', 13],
      ['}'],
    ]),
    python: listing(N, [
      ['def find(parent, x):', 1],
      ['    r = x', 2],
      ['    while parent[r] != r:', 3],
      ['        r = parent[r]', 3],
      ['    while parent[x] != r:', 4],
      ['        nxt = parent[x]', 5],
      ['        parent[x] = r', 5],
      ['        x = nxt', 5],
      ['    return r', 6],
      [''],
      ['def union(parent, rank, a, b):', 7],
      ['    ra, rb = find(parent, a), find(parent, b)', 8],
      ['    if ra == rb:', 9],
      ['        return', 9],
      ['    if rank[ra] < rank[rb]:', 10],
      ['        ra, rb = rb, ra', 10],
      ['    elif rank[ra] == rank[rb] and rb < ra:', 11],
      ['        ra, rb = rb, ra', 11],
      ['    parent[rb] = ra', 12],
      ['    if rank[ra] == rank[rb]:', 13],
      ['        rank[ra] += 1', 13],
    ]),
    cpp: listing(N, [
      ['int find(vector<int>& parent, int x) {', 1],
      ['    int r = x;', 2],
      ['    while (parent[r] != r) r = parent[r];', 3],
      ['    while (parent[x] != r) {', 4],
      ['        int next = parent[x];', 5],
      ['        parent[x] = r;', 5],
      ['        x = next;', 5],
      ['    }'],
      ['    return r;', 6],
      ['}'],
      [''],
      ['void unite(vector<int>& parent, vector<int>& rank, int a, int b) {', 7],
      ['    int ra = find(parent, a), rb = find(parent, b);', 8],
      ['    if (ra == rb) return;', 9],
      ['    if (rank[ra] < rank[rb]) swap(ra, rb);', 10],
      ['    else if (rank[ra] == rank[rb] && rb < ra) swap(ra, rb);', 11],
      ['    parent[rb] = ra;', 12],
      ['    if (rank[ra] == rank[rb]) rank[ra]++;', 13],
      ['}'],
    ]),
    java: listing(N, [
      ['static int find(int[] parent, int x) {', 1],
      ['    int r = x;', 2],
      ['    while (parent[r] != r) r = parent[r];', 3],
      ['    while (parent[x] != r) {', 4],
      ['        int next = parent[x];', 5],
      ['        parent[x] = r;', 5],
      ['        x = next;', 5],
      ['    }'],
      ['    return r;', 6],
      ['}'],
      [''],
      ['static void union(int[] parent, int[] rank, int a, int b) {', 7],
      ['    int ra = find(parent, a), rb = find(parent, b);', 8],
      ['    if (ra == rb) return;', 9],
      ['    if (rank[ra] < rank[rb]) { int t = ra; ra = rb; rb = t; }', 10],
      ['    else if (rank[ra] == rank[rb] && rb < ra) { int t = ra; ra = rb; rb = t; }', 11],
      ['    parent[rb] = ra;', 12],
      ['    if (rank[ra] == rank[rb]) rank[ra]++;', 13],
      ['}'],
    ]),
  },
};
