/** Real-language listings for quick sort (Lomuto), line-mapped to the pseudocode
 *  in index.ts. Display only; src/algorithms/_code runs them against `reference`.
 *  C++ defines partition first so it is declared before quickSort calls it. */

import { listing } from '@/algorithms/_code/listing';
import type { CodeListing, RealLanguage } from '@/algorithms/types';

const N = 12;

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  lomuto: {
    js: listing(N, [
      ['function quickSort(a, lo, hi) {', 1],
      ['  if (lo >= hi) return;', 2],
      ['  const p = partition(a, lo, hi);', 3],
      ['  quickSort(a, lo, p - 1);', 4],
      ['  quickSort(a, p + 1, hi);', 5],
      ['}'],
      [''],
      ['function partition(a, lo, hi) {', 6],
      ['  const pivot = a[hi];', 7],
      ['  let i = lo - 1;', 7],
      ['  for (let j = lo; j < hi; j++) {', 8],
      ['    if (a[j] < pivot) {', 9],
      ['      i++;', 10],
      ['      [a[i], a[j]] = [a[j], a[i]];', 10],
      ['    }'],
      ['  }'],
      ['  [a[i + 1], a[hi]] = [a[hi], a[i + 1]];', 11],
      ['  return i + 1;', 12],
      ['}'],
    ]),
    python: listing(N, [
      ['def quick_sort(a, lo, hi):', 1],
      ['    if lo >= hi:', 2],
      ['        return', 2],
      ['    p = partition(a, lo, hi)', 3],
      ['    quick_sort(a, lo, p - 1)', 4],
      ['    quick_sort(a, p + 1, hi)', 5],
      [''],
      ['def partition(a, lo, hi):', 6],
      ['    pivot = a[hi]', 7],
      ['    i = lo - 1', 7],
      ['    for j in range(lo, hi):', 8],
      ['        if a[j] < pivot:', 9],
      ['            i += 1', 10],
      ['            a[i], a[j] = a[j], a[i]', 10],
      ['    a[i + 1], a[hi] = a[hi], a[i + 1]', 11],
      ['    return i + 1', 12],
    ]),
    cpp: listing(N, [
      ['int partition(vector<int>& a, int lo, int hi) {', 6],
      ['    int pivot = a[hi];', 7],
      ['    int i = lo - 1;', 7],
      ['    for (int j = lo; j < hi; j++) {', 8],
      ['        if (a[j] < pivot) {', 9],
      ['            i++;', 10],
      ['            swap(a[i], a[j]);', 10],
      ['        }'],
      ['    }'],
      ['    swap(a[i + 1], a[hi]);', 11],
      ['    return i + 1;', 12],
      ['}'],
      [''],
      ['void quickSort(vector<int>& a, int lo, int hi) {', 1],
      ['    if (lo >= hi) return;', 2],
      ['    int p = partition(a, lo, hi);', 3],
      ['    quickSort(a, lo, p - 1);', 4],
      ['    quickSort(a, p + 1, hi);', 5],
      ['}'],
    ]),
    java: listing(N, [
      ['static void quickSort(int[] a, int lo, int hi) {', 1],
      ['    if (lo >= hi) return;', 2],
      ['    int p = partition(a, lo, hi);', 3],
      ['    quickSort(a, lo, p - 1);', 4],
      ['    quickSort(a, p + 1, hi);', 5],
      ['}'],
      [''],
      ['static int partition(int[] a, int lo, int hi) {', 6],
      ['    int pivot = a[hi];', 7],
      ['    int i = lo - 1;', 7],
      ['    for (int j = lo; j < hi; j++) {', 8],
      ['        if (a[j] < pivot) {', 9],
      ['            i++;', 10],
      ['            int t = a[i]; a[i] = a[j]; a[j] = t;', 10],
      ['        }'],
      ['    }'],
      ['    int t = a[i + 1]; a[i + 1] = a[hi]; a[hi] = t;', 11],
      ['    return i + 1;', 12],
      ['}'],
    ]),
  },
};
