/** Real-language listings for recursive DFS with discovery/finish times.
 *  Same semantics as the generator: undirected edges, neighbours in ascending
 *  id, the outer loop over every node in ascending id, one clock for d and f.
 *  `map[p - 1]` lists the listing lines (1-based) for pseudocode line p.
 *  Every listing is executed against `reference` in dfs/code.test.ts. */

import type { CodeListing, RealLanguage } from '@/algorithms/types';

const js: CodeListing = {
  lines: [
    'function dfsTimes(n, edges) {',
    '  const adj = Array.from({ length: n }, () => []);',
    '  for (const [a, b] of edges) {',
    '    adj[a].push(b);',
    '    adj[b].push(a);',
    '  }',
    '  for (const list of adj) list.sort((x, y) => x - y);',
    '  const visited = new Array(n).fill(false);',
    '  const d = new Array(n).fill(0);',
    '  const f = new Array(n).fill(0);',
    '  let time = 0;',
    '',
    '  function dfs(u) {',
    '    visited[u] = true;',
    '    d[u] = ++time;',
    '    for (const v of adj[u]) {',
    '      if (!visited[v]) {',
    '        dfs(v);',
    '      }',
    '    }',
    '    f[u] = ++time;',
    '  }',
    '',
    '  for (let s = 0; s < n; s++) {',
    '    if (!visited[s]) dfs(s);',
    '  }',
    '  return { d, f };',
    '}',
  ],
  map: [[2, 3, 4, 5, 7, 8, 9, 10, 11], [24], [25], [13], [14, 15], [16], [17], [18], [21]],
};

const python: CodeListing = {
  lines: [
    'def dfs_times(n, edges):',
    '    adj = [[] for _ in range(n)]',
    '    for a, b in edges:',
    '        adj[a].append(b)',
    '        adj[b].append(a)',
    '    for nbrs in adj:',
    '        nbrs.sort()',
    '    visited = [False] * n',
    '    d = [0] * n',
    '    f = [0] * n',
    '    time = 0',
    '',
    '    def dfs(u):',
    '        nonlocal time',
    '        visited[u] = True',
    '        time += 1',
    '        d[u] = time',
    '        for v in adj[u]:',
    '            if not visited[v]:',
    '                dfs(v)',
    '        time += 1',
    '        f[u] = time',
    '',
    '    for s in range(n):',
    '        if not visited[s]:',
    '            dfs(s)',
    '    return d, f',
  ],
  map: [[2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [24], [25, 26], [13], [14, 15, 16, 17], [18], [19], [20], [21, 22]],
};

const cpp: CodeListing = {
  lines: [
    'struct DfsTimes {',
    '    std::vector<std::vector<int>> adj;',
    '    std::vector<bool> visited;',
    '    std::vector<int> d, f;',
    '    int time = 0;',
    '',
    '    DfsTimes(int n, const std::vector<std::pair<int, int>>& edges)',
    '        : adj(n), visited(n, false), d(n), f(n) {',
    '        for (auto [a, b] : edges) {',
    '            adj[a].push_back(b);',
    '            adj[b].push_back(a);',
    '        }',
    '        for (auto& nbrs : adj) std::sort(nbrs.begin(), nbrs.end());',
    '        for (int s = 0; s < n; s++) {',
    '            if (!visited[s]) dfs(s);',
    '        }',
    '    }',
    '',
    '    void dfs(int u) {',
    '        visited[u] = true;',
    '        d[u] = ++time;',
    '        for (int v : adj[u]) {',
    '            if (!visited[v]) {',
    '                dfs(v);',
    '            }',
    '        }',
    '        f[u] = ++time;',
    '    }',
    '};',
  ],
  map: [[5, 7, 8, 9, 10, 11, 13], [14], [15], [19], [20, 21], [22], [23], [24], [27]],
};

const java: CodeListing = {
  lines: [
    'class DfsTimes {',
    '    List<List<Integer>> adj = new ArrayList<>();',
    '    boolean[] visited;',
    '    int[] d, f;',
    '    int time = 0;',
    '',
    '    DfsTimes(int n, int[][] edges) {',
    '        for (int i = 0; i < n; i++) adj.add(new ArrayList<>());',
    '        for (int[] e : edges) {',
    '            adj.get(e[0]).add(e[1]);',
    '            adj.get(e[1]).add(e[0]);',
    '        }',
    '        for (List<Integer> nbrs : adj) Collections.sort(nbrs);',
    '        visited = new boolean[n];',
    '        d = new int[n];',
    '        f = new int[n];',
    '        for (int s = 0; s < n; s++) {',
    '            if (!visited[s]) dfs(s);',
    '        }',
    '    }',
    '',
    '    void dfs(int u) {',
    '        visited[u] = true;',
    '        d[u] = ++time;',
    '        for (int v : adj.get(u)) {',
    '            if (!visited[v]) {',
    '                dfs(v);',
    '            }',
    '        }',
    '        f[u] = ++time;',
    '    }',
    '}',
  ],
  map: [[5, 7, 8, 9, 10, 11, 13, 14, 15, 16], [17], [18], [22], [23, 24], [25], [26], [27], [30]],
};

export const code: Record<string, Partial<Record<RealLanguage, CodeListing>>> = {
  recursive: { js, python, cpp, java },
};
